INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Boltysh','24','65.17','Chondrite','48.45','32.10','11','1');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Dellen','19','89.0 ','Stone','61.48','16.48','10','2');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Dobele','4.5','290','-','56.35','23.15','6','3');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Gardnos','5','500','Chondrite','60.39','9.0','8','4');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Granby','3','470','-','58.25','14.56','10','5');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Hummeln','1.2','443','Chondrite','57.22','16.15','10','6');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Ilumetsä','0.08',' 0.0066','-','57.58','27.25','2','7');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Ilyinets','8.5','378','Iron','49.7','29.6','11','8');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Iso-Naakkima','3','1000','-','62.11','27.9','3','9');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Kaalijärv','0.11','0.004','-','58.24','22.40','2','10');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Karikkoselkä','1.5','230','-','62.13','25.15','3','11');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Keurusselkä','30','1800','-','62.8','24.36','3','12');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Kärdla','7','455','-','59.1','22.46','2','13');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Lappajärvi','23','76.20','Chondrite','63.12','23.42','3','14');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Lockne','7.5','458','-','63.0','14.49','10','15');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Logoisk','15','42.3','-','54.12','27.48','1','16');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Lumparn','9','1000','-','60.9','20.6','3','17');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Mien','9','121.0','Stone','56.25','14.52','10','18');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Mizarai','5','500','-','54.1','23.54','7','19');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Mjølnir','40','142.0','-','73.48','29.40','8','20');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Morasko','0.1','0.01','Octahedrite fragments','52.29','16.54','9','21');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Målingen','1','458','-','62.55','14.33','10','22');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Neugrund','8','535','-','59.20','23.40','2','23');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Obolon','20','169','Iron','49.35','32.55','11','24');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Paasselkä','10','1800','-','62.2','29.5','3','25');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Ries','24','15.1','Achondrite','48.53','10.37','5','26');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Ritland','2.7','520','-','59.14','6.26','8','27');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Rochechouart','23','201','Chondrite Iron','45.50','0.56','4','28');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Rotmistrovka','2.7','120','-','49.0','32.0','11','29');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Saarijärvi','1.5','600','-','65.17','28.23','3','30');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Siljan','52','376.8','-','61.2','14.52','10','31');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Steinheim','3.8','15','-','48.41','10.4','5','32');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Suvasvesi N','4','1000','-','62.42','28.10','3','33');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Suvasvesi S','3.8','250','-','62.36','28.13','3','34');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Sääksjärvi','6','560','Stony-iron','61.24','22.24','3','35');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Söderfjärden','6.6','600','-','63.2','21.35','3','36');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Ternovka','11','280','Chondrite','48.08','33.31','11','37');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Tvären','2','455','-','58.46','17.25','10','38');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Vepriai','8','160','-','55.5','24.35','7','39');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Zapadnaya','3.2','165','-','49.44','29.0','11','40');
INSERT INTO [dbo].[Crater_Details] (Crater_Name,Diameter,Age,Composition_Type,Latitude,Longitude,LocationID,CraterID) VALUES ('Zeleny Gai','3.5','80','-','48.4','32.45','11','41');
